export const images = [
  {
    name:"potato",
    url:"/images/buyers_image/potato.png"
  },
  {
    name:"corn",
    url:"/images/buyers_image/corn.png"
  },
  {
    name:"nuts",
    url:"/images/buyers_image/nuts.png"
  },
  {
    name:"ginger",
    url:"/images/buyers_image/ginger.png"
  },
  {
    name:"cassava",
    url:"/images/buyers_image/cassava.png"
  },
  {
    name:"onions",
    url:"/images/buyers_image/onions.png"
  },
  {
    name:"oliveoil",
    url:"/images/buyers_image/oliveoil.png"
  },
  {
    name:"orange",
    url:"/images/buyers_image/orange.png"
  },
  {
    name:"cassavaII",
    url:"/images/buyers_image/cassavaII.png"
  },
  {
    name:"strawberry",
    url:"/images/buyers_image/strawberry.png"
  },
  {
    name:"avocado",
    url:"/images/buyers_image/avocado.png"
  },
  {
    name:"rice",
    url:"/images/buyers_image/rice.png"
  },
  {
    name:"bellpepper",
    url:"/images/buyers_image/bellpepper.png"
  },
  {
    name:"pineapple",
    url:"/images/buyers_image/pineapple.png"
  }
]